### ISSUE TITLE
Train data

### ISSUE THREAD

**Issue by ihameed11** [tsrobinson/rMIDAS#14]
when I try to train data " adult data"
this message showed up
Error in py_call_impl(callable, dots$args, dots$keywords) :
ValueError: Imputation target contains no missing values. Please ensure missing values are encoded as type np.nan
I tried to replace the missing values with np.nan but same message came

**Comment by tsrobinson** [comment]
Hi @ihameed11, so we can troubleshoot this could you provide us with the following:
* Operating system
* Python, numpy, and tensorflow versions
* A minimum working example that raises this error

Thanks!

**Comment by tsrobinson** [comment]
I am closing this issue -- please just reopen it if you are still running into issues.
