### ISSUE TITLE
tensorflow dependency not listed in README

### ISSUE THREAD

**Issue by nick-youngblut** [tsrobinson/rMIDAS#17]
It would be helpful if the README listed all of the python dependencies for rMIDAS (eg., tensorflow). Better yet, it would be helpful to have all such dependencies listed in a conda env yaml file, and the info on creating that conda env in the README.

**Comment by tsrobinson** [comment]
Thanks @nick-youngblut -- duly noted, and agree this could be solved by provindg a conda env yaml file. We will resolve this asap.

**Comment by tsrobinson** [comment]
This has now been fixed in the latest development version and will be pushed to CRAN asap. Thanks!
