### ISSUE TITLE
set_python_env: python param

### ISSUE THREAD

**Issue by nick-youngblut** [tsrobinson/rMIDAS#18]
For `set_python_env()`, the `python` parameter is a bit misleading, since it only really applies for `type="auto"`. Maybe using a neutral parameter name such as `x` would help to clarify.

**Comment by ghost** [comment]
Hey @nick-youngblut If you wanna use a manual  way u can use 'reticulate::use_'. Note: If u wish to set a custom binary/environment, this must be completed prior to the first call to either 'train()' or 'complete()'. further argument passed to 'reticulate::use_condaenv()'

**Comment by tsrobinson** [comment]
This has now been fixed in the latest development version and will be pushed to CRAN asap. Thanks again!
