### ISSUE TITLE
Replace source code copy with install_midas()

### ISSUE THREAD

**Issue by tsrobinson** [tsrobinson/rMIDAS#22]
Current behaviour: At present, the MIDAS algorithm is bundled as [Python source code](https://github.com/MIDASverse/rMIDAS/blob/master/inst/python/midas_base.py) in the R package, which is imported via reticulate the first time the user calls a python-reliant command in rMIDAS.

Suggested behaviour: Include an install_midas() function that downloads the latest version of MIDASpy from PyPI into the active Python version (via pip). When the user calls a python-reliant command, reticulate loads this package in Python.

This would remove the need to maintain a shadow version of the MIDAS source code directly in the R package.

**Comment by edvinskis** [comment]
Although maintaining a shadow copy of the MIDAS source code in the R package is still necessary, the recent updates in rMIDAS v0.5.0 have been designed to optimize the user experience. This includes changes made for interactive sessions, as well as enhanced documentation for non-interactive sessions. We value user feedback, and the 'install_midas()' function can still be added at any time. However, it's worth noting that the current auto-setup in interactive mode essentially achieves the same as what the 'install_midas()' function would. With this in mind, I will be closing this issue.
